
language: python
python:
  - "3.6"
dist: xenial
install:
  - pip install --progress-bar off -r requirements.txt
  - pip install --progress-bar off pytest-cov pytest-faulthandler codecov
script:
  # run tests
  - py.test --cov-report=xml --cov=hercules_sync

  # build documentation
  - cd docs/sphinx
  - make html
  - touch _build/html/.nojekyll
  - cd ../../

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local_dir: docs/sphinx/_build/html

after_success:
  - codecov
