version: '3'

services:
  hercules_sync:
    image: hercules-sync
    build:
      context: .
      dockerfile: Dockerfile

    ports:
     - "5000:5000"
    environment:
      - FLASK_CONFIG=production
      # CONFIG - Change the default values below
      - GITHUB_OAUTH=
      - WBAPI=
      - WBSPARQL= 
      - WBUSER=
      - WBPASS=
      - WEBHOOK_SECRET=
      - URIS_FACTORY=
