version: '3'

services:
  hercules_sync:
    image: wesogroup/hercules_sync:v0.1.6
    network_mode: host
    ports:
     - "5000:5000"
    environment:
      - FLASK_CONFIG=production
      # CONFIG - Change the default values below
      - GITHUB_OAUTH=oauth_key
      - WBAPI=wikibase_api_endpoint
      - WBSPARQL=wikibase_sparql_endpoint
      - WBUSER=wikibase_username
      - WBPASS=wikibase_password
      - WEBHOOK_SECRET=webhook_secret_key
