name: Mirror @ Murcia Organization

on: [push, delete]

jobs:
  mirror:
    runs-on: ubuntu-18.04
    steps:
    - name: mirror
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.IZERTIS_GITHUB_SSH_KEY }}
      with:
        source-repo: 'git@github.com:weso/hercules-sync.git'
        destination-repo: 'git@github.com:HerculesCRUE/ib-hercules-sync.git'
